package tenis;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.HeadlessException;
import javax.swing.table.DefaultTableModel;
import tenis.Juego.Marcador;

/**
 *
 * @author CHURITA
 */
public class MarcadorTabla extends javax.swing.JFrame {

    /**
     * Creates new form MarcadorEsp
     */
    private Marcador marcador;
    String j1,j2;

    public Marcador getMarcador() {
        return marcador;
    }

    public void setMarcador(Marcador marcador,String j1,String j2) {
        this.j1=j1;
        this.j2=j2;
        this.marcador = marcador;
        this.label_idioma.setText(marcador.getIdioma().getClass().getSimpleName());
        this.label_puntuacion.setText(marcador.getIdioma().love() + " " + marcador.getIdioma().all());
        tabla = new DefaultTableModel();
        tabla.addColumn(j1);
        tabla.addColumn(j2);
        tabla.addColumn("Puntuacion");
        this.jTable1.setModel(tabla);
    }

    public void setDatos(int p1, int p2) {
        String[] rowData = new String[3];
        rowData[0] = Integer.toString(p1);
        rowData[1] = Integer.toString(p2);
        rowData[2] = marcador.EstablecerMarcador(p1, p2);
        this.label_puntuacion.setText(rowData[2]);
        tabla.addRow(rowData);
    }

    public void reiniciar() {
        tabla = new DefaultTableModel();
        tabla.addColumn(j1);
        tabla.addColumn(j2);
        tabla.addColumn("Puntuacion");
        this.jTable1.setModel(tabla);
    }
    private DefaultTableModel tabla;

    public MarcadorTabla(String j1,String j2) {
        super();
        this.j1=j1;
        this.j2=j2;
        initComponents();
        tabla = new DefaultTableModel();
        tabla.addColumn(j1);
        tabla.addColumn(j2);
        tabla.addColumn("Puntuacion");
        this.jTable1.setModel(tabla);
    }

    public MarcadorTabla() throws HeadlessException {
        initComponents();
        tabla = new DefaultTableModel();
        tabla.addColumn(j1);
        tabla.addColumn(j2);
        tabla.addColumn("Puntuacion");
        this.jTable1.setModel(tabla);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label_puntuacion = new javax.swing.JLabel();
        label_idioma = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Deutsch");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        label_puntuacion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        label_puntuacion.setForeground(new java.awt.Color(0, 102, 102));
        label_puntuacion.setText("Puntuación :  Cero iguales");

        label_idioma.setFont(new java.awt.Font("Zrnic", 0, 48)); // NOI18N
        label_idioma.setForeground(new java.awt.Color(0, 0, 102));
        label_idioma.setText("Español");

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 0, 12), new java.awt.Color(255, 51, 102))); // NOI18N
        jTable1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 0, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Jugador 1", "Jugador 2", "Marcador"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(label_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_puntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_idioma;
    public javax.swing.JLabel label_puntuacion;
    // End of variables declaration//GEN-END:variables
}
